weaponBases = {
    "tier1PSIWeapon": {
        "baseName": "tier1PSIWeapon",
        "minimumItemLvl": 0,
        "minimumInstabilityLvl": 0,
        "baseWeight": 1,
        "names": ["Rickety PSI glove", "Rusted PSI glove"],
        "attackCategory": "psi",
        "implicitMods": [],
        "images": [],
        "baseTags": ["weapon", "psi"],
    },
    "tier2PSIWeapon": {
        "baseName": "tier2PSIWeapon",
        "minimumItemLvl": 10,
        "minimumInstabilityLvl": 0,
        "baseWeight": 2,
        "names": ["Power Glove", "PSI glove"],
        "attackCategory": "psi",
        "implicitMods": [],
        "images": [],
        "baseTags": ["weapon", "psi"],
    },
    "tier3PSIWeapon": {
        "baseName": "tier3PSIWeapon",
        "minimumItemLvl": 20,
        "minimumInstabilityLvl": 0,
        "baseWeight": 2,
        "names": ["PSI Manipulator"],
        "attackCategory": "psi",
        "implicitMods": [],
        "images": [],
        "baseTags": ["weapon", "psi"],
    },

    "tier1AssaultWeapon": {
        "baseName": "tier1AssaultWeapon",
        "minimumItemLvl": 0,
        "minimumInstabilityLvl": 0,
        "baseWeight": 1,
        "names": ["Rusty Shank", "Baseball Bat", "Broken Baton"],
        "attackCategory": "assault",
        "implicitMods": [],
        "images": [],
        "baseTags": ["weapon", "assault"],
    },
    "tier2AssaultWeapon": {
        "baseName": "tier2AssaultWeapon",
        "minimumItemLvl": 10,
        "minimumInstabilityLvl": 0,
        "baseWeight": 2,
        "names": ["Stun Baton"],
        "attackCategory": "assault",
        "implicitMods": [],
        "images": [],
        "baseTags": ["weapon", "assault"],
    },
    "tier3AssaultWeapon": {
        "baseName": "tier3AssaultWeapon",
        "minimumItemLvl": 20,
        "minimumInstabilityLvl": 0,
        "baseWeight": 2,
        "names": ["Plasma Poker"],
        "attackCategory": "assault",
        "implicitMods": [],
        "images": [],
        "baseTags": ["weapon", "assault"],
    },

    "tier1InsanityWeapon": {
        "baseName": "tier1InsanityWeapon",
        "minimumItemLvl": 0,
        "minimumInstabilityLvl": 10,
        "baseWeight": 1,
        "names": ["Dart Gun"],
        "attackCategory": "tactics",
        "implicitMods": [],
        "images": [],
        "modMultiplier": 1.2,
        "instabilityMultiplier": 1.3,
        "baseTags": ["weapon", "tactics"],
    },
    "tier2InsanityWeapon": {
        "baseName": "tier2InsanityWeapon",
        "minimumItemLvl": 10,
        "minimumInstabilityLvl": 20,
        "baseWeight": 1,
        "names": ["Rubber Chicken"],
        "attackCategory": "assault",
        "implicitMods": [],
        "images": [],
        "modMultiplier": 1.4,
        "instabilityMultiplier": 1.4,
        "baseTags": ["weapon", "assault"],
    },
    "tier3InsanityWeapon": {
        "baseName": "tier3InsanityWeapon",
        "minimumItemLvl": 10,
        "minimumInstabilityLvl": 30,
        "baseWeight": 2,
        "names": ["Mysterious Orb"],
        "attackCategory": "psi",
        "implicitMods": [],
        "images": [],
        "modMultiplier": 1.5,
        "instabilityMultiplier": 1.5,
        "baseTags": ["weapon", "psi"],
    },
}

bootsBases = {
    "tier1Boots": {
        "baseName": "tier1Boots",
        "minimumItemLvl": 0,
        "minimumInstabilityLvl": 0,
        "baseWeight": 1,
        "names": ["Leather Boots"],
        "implicitMods": [],
        "images": [],
        "baseTags": ["armor", "boots"],
    },
}

baseTypes = weaponBases | bootsBases
